webAppProje/WebApp/WebApp/Controllers/ClientOrdersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebApp.Models;
using WebApp.Services;

namespace WebApp.Controllers
{
    [Authorize]
    [Route("/Client/Orders/{action=Index}/{id?}")]
    public class ClientOrdersController : Controller
    {
        private readonly ApplicationDbContext context;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly int pageSize = 5;

        public ClientOrdersController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            this.context = context;
            this.userManager = userManager;
        }
        public async Task<IActionResult> Index(int pageIndex)
        {
            var currentUser = await userManager.GetUserAsync(User);
            if (currentUser == null)
            {
                return RedirectToAction("Index", "Home");
            }

            IQueryable<Order> query = context.Orders.Include(o => o.Items).OrderByDescending(o => o.Id)
                .Where(o => o.ClientId == currentUser.Id);

            if (pageIndex <= 0)
            {
                pageIndex = 1;
            }

            decimal count = query.Count();
            int totalPages = (int)Math.Ceiling(count / pageSize);

            query = query.Skip((pageIndex - 1) * pageSize).Take(pageSize);

            var orders = query.ToList();

            ViewBag.Orders = orders;
            ViewBag.PageSize = pageSize;
            ViewBag.TotalPages = totalPages;
            return View();
        }
        public async Task<IActionResult> Details(int id)
        {
            var currentUser = await userManager.GetUserAsync(User);
            if (currentUser == null)
            {
                return RedirectToAction("Index", "Home");
            }

            var order = context.Orders.Include(o => o.Items).ThenInclude(oi => oi.Product).Where(o => o.ClientId == currentUser.Id)
                .FirstOrDefault(o => o.Id == id);
            if (order == null)
            {
                return RedirectToAction("Index");
            }

            return View(order);
        }
    }
}

webAppProje/WebApp/WebApp/Views/ClientOrders/Details.cshtml
@model Order
@{
    string paymentBadgeColor = "bg-danger";
    if (Model.PaymentStatus == "pending")
    {
        paymentBadgeColor = "bg-warning text-dark";
    }
    else if (Model.PaymentStatus == "accepted")
    {
        paymentBadgeColor = "bg-success";
    }
    else if (Model.PaymentStatus == "canceleed")
    {
        paymentBadgeColor = "bg-secondary";
    }

    string orderBadgeColor = "bg-danger";
    if (Model.OrderStatus == "pending")
    {
        paymentBadgeColor = "bg-warning text-dark";
    }
    else if (Model.OrderStatus == "accepted")
    {
        paymentBadgeColor = "bg-success";
    }
    else if (Model.OrderStatus == "canceleed")
    {
        paymentBadgeColor = "bg-secondary";
    }
    else if (Model.OrderStatus == "shipped")
    {
        paymentBadgeColor = "bg-primary";
    }
    else if (Model.OrderStatus == "delivered")
    {
        paymentBadgeColor = "bg-success";
    }
    else if (Model.OrderStatus == "returned")
    {
        paymentBadgeColor = "bg-info text-dark";
    }
    else if (Model.OrderStatus == "deleted")
    {
        paymentBadgeColor = "bg-dark";
    }
}

<h3 class="text-center mb-4">Order Details</h3>

<a class="btn btn-link" asp-controller="ClientOrders" asp-action="Index">Orders</a>

<div class="row mb-4">
    <div class="col">
        <div class="border rounded py-3 px-4 h-100">
            <h3 class="mb-4">Order</h3>

            <div class="row mb-2 pb-2 border-bottom">
                <div class="col">Order ID</div>
                <div class="col">@Model.Id</div>
            </div>
            <div class="row mb-2 pb-2 border-bottom">
                <div class="col">Delivery Address</div>
                <div class="col">@Model.DeliveryAddress</div>
            </div>
            <div class="row mb-2 pb-2 border-bottom">
                <div class="col">Payment Method</div>
                <div class="col">@Model.PaymentMethod</div>
            </div>
            <div class="row mb-2 pb-2 border-bottom">
                <div class="col">Payment Status</div>
                <div class="col">
                    <span class="badge rounded-pill @paymentBadgeColor">@Model.PaymentStatus</span>
                </div>
            </div>
            <div class="row mb-2 pb-2 border-bottom">
                <div class="col">Order Status</div>
                <div class="col">
                    <span class="badge rounded-pill @orderBadgeColor">@Model.OrderStatus</span>
                </div>
            </div>
            <div class="row mb-2">
                <div class="col">Order Date</div>
                <div class="col">@Model.CreatedAt</div>
            </div>
        </div>
    </div>
   
</div>

<table class="table">
    <thead>
        <tr>
            <th style="width: 100px">Description</th>
            <th></th>
            <th style="width: 100px">Units</th>
            <th style="width: 100px">Amount</th>
        </tr>
    </thead>
    <tbody>
        @{
            decimal subtotal = 0;
            foreach (var item in Model.Items)
            {
                subtotal += item.UnitPrice * item.Quantity;
                <tr>
                    <td>
                        <img src="/products/@item.Product.ImageFileName" width="100" alt="..." />
                    </td>
                    <td>
                        <h4>
                            <a style="text-decoration: none; color: inherit;" asp-controller="Store" asp-action="Details"
                               asp-route-id="@item.Product.Id">
                                @item.Product.Name
                            </a>
                        </h4>
                        @item.Product.Category<br />
                        @(item.UnitPrice)$
                    </td>
                    <td>@item.Quantity</td>
                    <td>@(item.UnitPrice * item.Quantity)$</td>
                </tr>
            }
        }
    </tbody>
</table>

<div class="ms-auto mb-3" style="width: 250px">
    <div class="row">
        <div class="col fw-bold">Subtotal:</div>
        <div class="col text-end">@(subtotal)$</div>
    </div>
    <div class="row">
        <div class="col fw-bold">Shipping Fee:</div>
        <div class="col text-end">@(Model.ShippingFee)$</div>
    </div>
    <div class="row">
        <div class="col fw-bold">Total:</div>
        <div class="col text-end">@(subtotal + Model.ShippingFee)$</div>
    </div>
</div>

webAppProje/WebApp/WebApp/Views/ClientOrders/Index.cshtml
@{
}
<h3 class="text-center mb-4">List of Orders</h3>

<table class="table">
    <thead>
        <tr>
            <th>Units</th>
            <th>Total</th>
            <th>Payment Method</th>
            <th>Payment Status</th>
            <th>Order Status</th>
            <th>Date</th>
            <th>Action</th>
        </tr>
    </thead>

    <tbody>
        @foreach (Order order in ViewBag.Orders)
        {
            int count = 0;
            decimal total = order.ShippingFee;
            foreach (OrderItem item in order.Items)
            {
                count += item.Quantity;
                total += item.Quantity * item.UnitPrice;
            }

            string paymentBadgeColor = "bg-danger";
            if (order.PaymentStatus == "pending")
            {
                paymentBadgeColor = "bg-warning text-dark";
            }
            else if (order.PaymentStatus == "accepted")
            {
                paymentBadgeColor = "bg-success";
            }
            else if (order.PaymentStatus == "canceleed")
            {
                paymentBadgeColor = "bg-secondary";
            }

            string orderBadgeColor = "bg-danger";
            if (order.OrderStatus == "pending")
            {
                paymentBadgeColor = "bg-warning text-dark";
            }
            else if (order.OrderStatus == "accepted")
            {
                paymentBadgeColor = "bg-success";
            }
            else if (order.OrderStatus == "canceleed")
            {
                paymentBadgeColor = "bg-secondary";
            }
            else if (order.OrderStatus == "shipped")
            {
                paymentBadgeColor = "bg-primary";
            }
            else if (order.OrderStatus == "delivered")
            {
                paymentBadgeColor = "bg-success";
            }
            else if (order.OrderStatus == "returned")
            {
                paymentBadgeColor = "bg-info text-dark";
            }
            else if (order.OrderStatus == "deleted")
            {
                paymentBadgeColor = "bg-dark";
            }

            <tr>
                <td>@count</td>
                <td>@(total)$</td>
                <td>@order.PaymentMethod</td>
                <td><span class="badge rounded-pill @paymentBadgeColor">@order.PaymentStatus</span></td>
                <td><span class="badge rounded-pill @orderBadgeColor">@order.OrderStatus</span></td>
                <td>@order.CreatedAt.ToString("MM/dd/yyyy")</td>
                <td>
                    <a class="btn btn-primary btn-sm" asp-controller="ClientOrders" asp-action="Details"
                       asp-route-id="@order.Id">Details</a>
                </td>

            </tr>
        }
    </tbody>
</table>
<nav>
    <ul class="pagination">
        @for (int i = 1; i <= ViewBag.totalPages; i++)
        {
            string active = "";
            if (i == ViewBag.pageIndex) active = "active";
            <li class="page-item @active">
                <a class="page-link" asp-route-pageIndex="@i">@i</a>
            </li>
        }
    </ul>
</nav>